-- CREATE TABLE notes (
--     id serial PRIMARY KEY ,
--     body CHARACTER VARYING ,
--     student_id INT,
--     FOREIGN KEY (student_id)
--         REFERENCES  students (id)
-- )

-- INSERT INTO notes (body, student_id)
--     VALUES ('Hello World!', 1);
-- INSERT INTO notes (body, student_id)
--     VALUES ('I wonder if the moon is made of cheese...', NULL);
-- INSERT INTO notes (body, student_id)
--     VALUES ('There''s something I want to say...', 2);

-- SELECT * FROM notes;
--
-- SELECT * FROM students
--     INNER JOIN notes n on students.id = n.student_id;
--
-- SELECT * FROM students
--     LEFT JOIN notes n on students.id = n.student_id;
--
-- SELECT * FROM students
--     RIGHT JOIN notes n on students.id = n.student_id;
--
-- SELECT * FROM students
--     FULL OUTER JOIN notes n on students.id = n.student_id;